codilime/veles

- include/ui/veles_mainwindow.h
- src/ui/veles_mainwindow.cc
MainWindowWithDetachableDockWidgets::dock_widgets_with_no_title_bars_ doesn't affect possibility to reorder tabs.
> Tabs in main window can always be reordered.

- src/ui/veles_mainwindow.cc
Explicitly calling QLayout::update in MainWindowWithDetachableDockWidgets::updateDocksAndTabs. It should prevent undesired behavior related to top level windows not refreshing accordingly.
> Improved MainWindowWithDetachableDockWidgets::updateDocksAndTabs.

- README.rst
- add caveat about qt 5.5 and tabs
- fix zlib package name on ubuntu
- remove dependent packages (zlib1g-dev depends on zlib1g etc.)
- fix typos
> Readme fixes.

- src/ui/hexeditwidget.cc
For now it doesn't offer any functionality in hex-view so it's
better to omit it.
> Hide hex view minimap

- python/veles/db.py
- python/veles/proto/msgpackwrap.py
- python/veles/schema/fields.py
- python/veles/tests/db/test_db.py
- python/veles/tests/util/test_bigint.py
- python/veles/util/bigint.py
This encoding allows us to store bigints in the database (pos_start
and pos_end columns) and have them correctly sorted.
Also, while we're at it, let's replace the current msgpack encoding
scheme, since it's quite redundant.
> Order-preserving bigint encoding.

- python/make_blob
- python/upload_elf
- python/veles/asrv/proto.py
- python/veles/asrv/srv.py
- python/veles/proto/exceptions.py
- python/veles/proto/messages.py
- python/veles/proto/msgpackwrap.py
- python/veles/proto/node.py
- python/veles/schema/fields.py
- python/veles/schema/model.py
- python/veles/scli/client.py
- python/veles/tests/schema/test_fields.py
- python/veles/tests/schema/test_model.py
- python/veles/tests/schema/test_polymodel.py
Changes:
- schema validation errors raise SchemaError.
- setting value of a field and deserializing it are now distinct operations
and are more closely validated - it is now illegal to assign a dict to
a model field, for example.
- Extension replaced with new NodeID and BinData fields.
- Array split into List and Set, which now only accept list/set, respectively.
- the type parameters of List/Set/Map now come before the optional parameter,
and are intended to be used as positional params.
- a default value may now be set for a field.
- List/Set/Map have a default value of []/set()/{} by default.
- a new UnsignedInteger field is introduced (it's just an Integer with
minimum=0)
- SmallInteger and SmallUnsignedInteger fields are introduced - these
are limitted to int64_t and uint64_t range, …
> Schema cleanups & improvements

- python/srv
This is fix for regression introduced in PR #87 where wrong exception
type was assumed to be thrown by add_signal_handler on Windows
> Fix Python srv launcher on Windows

- python/veles/schema/fields.py
- python/veles/tests/schema/test_fields.py
To be used for params/results of methods that don't have params/results.
> schema: Add Empty field.

- CMakeLists.txt
- README.rst
- cmake/cppgen.cmake
- include/network/msgpackobject.h
- include/network/msgpackwrapper.h
- python/veles/cpp/generate.py
- python/veles/proto/exceptions.py
- python/veles/schema/fields.py
- python/veles/schema/model.py
- src/network/msgpackobject.cc
* Generate messages.h only when Python files it depends on changes
* Update README.rst
* use venv instead of virtualenv
* make fromMsgpack private
* check variant type when accessing MsgpackObject
and throw ConversionException on mismatch
* use Python defaults in C++ code where it was easy to do
* remove unneeded returned None from cpp_type in Model class
* throw ConversionException when non-optional field is not set
when trying to load or serialize Model
* Convert nullptr to Nil variant when unpacking msgpack::object
to our MsgpackObject variant
* Add dumpObject to MsgpackWrapper to directly pack supported objects
to msgpack packer
* Add method loadMessagePack to Model that loads it from msgpack::object
* Add method polymorphicLoad to PolymorphicModel that loads correct Model
based on …
> Many bugfixes and small improvements

- Jenkinsfile
Pipe commands swallow the exit codes from cmake so output from cmake is now
catched in to the file and then `cat`ed.
> Make compile failures stop the build

- python/veles/async_conn/tracer.py
- python/veles/cpp/generate.py
- python/veles/db/tracker.py
- python/veles/proto/check.py
- python/veles/proto/messages.py
- python/veles/proto/node.py
- python/veles/proto/operation.py
Protocol changes only - no implementation yet.
> Add triggers to the protocol.

- CMakeLists.txt
This is just a temporary solution to problem with our CMakeLists file.
Generally we shouldn't include files from other targets that current target
doesn't depend on - like how veles_visualization includes things from main_ui.
> Fix concurent build issue

- src/ui/dockwidget.cc
This should fix tabs blinking and severly reduces chances that it
crashes inside QTabBar with wrong internal indexes
> Fix most issues with reordering tabs in QTabBar

- CMakeLists.txt
CMAKE_OSX_DEPLOYMENT_TARGET documentation requires that it is set before
any project() and enable_language().
> Build macOS in a way that allows Python extension modules

- CMakeLists.txt
- include/ui/hexedit.h
- include/ui/hexeditwidget.h
- include/ui/shortcutedit.h
- include/ui/shortcutssettings.h
- include/ui/veles_mainwindow.h
- include/util/settings/shortcuts.h
- include/visualization/trigram.h
- src/ui/connectionmanager.cc
- src/ui/dockwidget.cc
- src/ui/hexedit.cc
- src/ui/hexeditwidget.cc
- src/ui/nodetreewidget.cc
- src/ui/nodewidget.cc
- src/ui/shortcutedit.cc
- src/ui/shortcutselection.ui
- src/ui/shortcutssettings.cc
- src/ui/shortcutssettings.ui
- src/ui/veles_mainwindow.cc
- src/util/settings/shortcuts.cc
- src/visualization/panel.cc
- src/visualization/trigram.cc
Keyboard shortcuts for all action types are saved in settings,
they are editable through new dialog available in file menu.
All existing QActions that weren't generated based on some data
were converted to support editing shortcuts for them.
> Add keyboard shortcuts editor

- src/ui/dockwidget.cc
Without it was possible that Qt sent another tabCloseRequested signal
for the same dock_widget which was already deleted, but not yet removed from
internal tabData pointer
> Call removeTab in tabCloseRequested

- python/veles/async_client/proto.py
- python/veles/proto/messages.py
- python/veles/scli/client.py
- python/veles/server/proto.py
Importing veles.server from veles.scli breaks Python 2 for obvious reasons.
Reported by mkow.
> Move PROTO_VERSION from veles.server to veles.proto

- python/make_blob
- python/upload_elf
- python/veles/scli/client.py
Fixes python2 problems with invalid type of client_name etc.
> scli: Use unicode_literals

- CMakeLists.txt
- Jenkinsfile
- README.rst
1. Add target lint to CMake to check against Google checks
2. Add target format to CMake to check against errors in code formatting
3. Add lint and format targets to Jenkinsfile and WarningsPublisher
4. Improve performance of builds on Windows
5. Bring back pipes and tee when gathering errors and warnings for WarningsPublisher
6. Do not use XCode generator for CMake. That allows building on MacOS with only Command Line Developer Tools installed
> clang-tidy, clang-format and Jenkinsfile improvements

- CMakeLists.txt
Add `@executable_path/../Frameworks` to RPATH on MacOSX, so Qt will be properly found after installing Veles on Mac.
> Fix RPATH on MacOSX

- CMakeLists.txt
- include/ui/fileblobitem.h
- include/ui/hexedit.h
- include/ui/nodetreewidget.h
- include/util/misc.h
- src/ui/fileblobmodel.cc
- src/ui/hexedit.cc
- src/util/misc.cc
- src/util/settings/theme.cc
Changes:
* `painter.drawText()` -> `painter.drawStaticText()` + text cache (20% speedup)
* Removed unused `QSettings settings;` in a frequently called function (6% speedup)
* Changed one `i`-based loop to foreach (1.5%)
* Many other small changes, each giving few percents.
> Make HexEdit::paintEvent() 2x faster

- Jenkinsfile
- README.rst
- test/build/Dockerfile
Created Dockerfile for verification of building instructions on Ubuntu. You can run it:
`$ rm -rf build && sudo docker build -f test/build/Dockerfile .`
Created Jenkins target for verification on CI.
Fixed missing instructions.
> Building instructions verfication using Docker

- CMakeLists.txt
When argument list to clang-format is longer than 8192 (limit for cmd.exe) on
Win32 platform use multiple targets and format files one by one.
> Use foreach in clang-format with long lists

- .clang-tidy
- CMakeLists.txt
- README.rst
Specifying -header-filter makes clang-tidy report errors also in header files.
Moved clang-tidy config to .clang-tidy file
> Use -header-filter to specify headers

- CMakeLists.txt
> Enable console on debug builds on Windows

- python/veles/util/helpers.py
- src/client/networkclient.cc
Fixes #316.
* Fixes certificate error on macOS (#316)
* Disallows valid SSL certificates with non-matching fingerprint
* Fixes a random unrelated issue in Python code (I'm too lazy to do a separate PR from this, sorry :P )
I have much more changes for networking code locally, but let's merge this fix for now.
> Fix networking

- src/ui/hexeditwidget.cc
Fixes possible crash on pressing <kbd>Insert</kbd>
> Fix a dangling reference (QStringLiteral quirk)

- src/ui/veles_mainwindow.cc
I added info about irc like @koriakin proposed in #351 between email and website address.
> Add contact info irc

- src/util/edit.cc
- Remove unnecessary `find`.
- Now all entirely overlapped nodes are removed in `while` loop (the last one too). `last_modified_node` will be never created unnecessarily.
> Code improvements in EditEngine

- src/ui/connectionmanager.cc
Waiting for a while avoids `QProcess: Destroyed while process ("python3") is still running.` error message.
> Waiting until local server exits

- include/ui/hexedit.h
- include/util/edit.h
- src/ui/hexedit.cc
- src/util/edit.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/codilime/veles/415)
> Fix empty file bugs

- include/util/settings/theme.h
- src/ui/fileblobmodel.cc
- src/ui/hexedit.cc
- src/ui/hexeditwidget.cc
- src/util/settings/theme.cc
This fixes the font interface and also makes hexeditor on macOS use fixed-width fonts.
Fixes #339.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/codilime/veles/420)
> Fix fixed-width fonts
