codilime/veles

include/visualisation/base.h
include/visualisation/digram.h
include/visualisation/trigram.h
src/ui/main.cc
src/visualisation/base.cc
src/visualisation/digram.cc
src/visualisation/panel.cc
src/visualisation/trigram.cc

Added functionality to base VisualisationWidget to make
this sort of async pre-calculation easy.

Calculate trigram auto-brightness in worker thread

---

CONTRIBUTING.md

Provide guidelines how one can contribute to Veles and also describe requirements about CLA

Contributing to Veles and Contributor License Agreement 

---

include/util/sampling/isampler.h
include/visualisation/base.h
src/util/sampling/isampler.cc
src/visualisation/base.cc
src/visualisation/panel.cc
test/util/sampling/isampler.cc

The root cause was not cleaning up callbacks :(

Fix various crashes when closing visualisations

---

include/network/server.h
src/network/server.cc

Includes fix to warning about comparsion

Some small fixes I forgot to include in previous patch

---

python/examples/parse_bmp.py
python/veles/objects/__init__.py
python/veles/objects/base.py
python/veles/objects/blob.py
python/veles/objects/chunk.py
python/veles/veles_api.py

A whole bunch of related refactors in python API.
Updated examples/parse_bmp.py accordingly.

Added separate python classes for blobs and chunks

---

python/veles/data/bindata.py
python/veles/tests/test_bindata.py

Strzelę do tego jeszcze jakieś testy i komentarze, ale funkcjonalnie jest IMO kompletne.
Reprezentacja stringowa jest trochę dyskusyjna, ale IMO najwygodniejsza...

BinData in python

---

python/veles/async_conn/conn.py
python/veles/async_conn/node.py
python/veles/async_conn/subscriber.py

Subsequent PRs will make asrv use this interface.

Add an interface to async connections.

---

Jenkinsfile

Made platform builds parallel and removed platforms parameter.
Sadly there are a lot of indentation changes

Parallel Jenkins builds

---

python/veles/db.py

- lots of NOT NULL clauses
- use application_id and user_version pragmas according to their purpose
- add an index covering parent and pos_start to help with get_list

db: A few minor improvements.

---

Jenkinsfile

30 for master branch and 5 for all other branches

Limit maximum builds kept in Jenkins history

---

python/veles/compatibility/pep487.py
python/veles/schema/model.py
python/veles/tests/schema/test_model.py

Fix model field ordering for Py3 versions < 3.6.

---

Jenkinsfile

* move builds to separate directories (for Ubuntu and MacOS).
* remove build directory after successful build
This should reduce greatly disk space requirements on our Jenkins nodes.
This change needs cleanup of Jenkins workspace after merge, so I recommend to apply this just after the release.

Clean workspace after successful builds

---

python/veles/db/backend.py
python/veles/server/conn.py
python/veles/tests/db/test_backend.py

This makes place for a few new classes in veles.db.

db: Database -> DbBackend.

---

python/veles/async_client/conn.py
python/veles/async_client/node.py
python/veles/async_conn/conn.py
python/veles/async_conn/node.py
python/veles/server/conn.py
python/veles/server/node.py
python/veles/server/query.py

The eventual goal of this PR series is to get rid of the AsyncNode class.

async_conn: Move getters and method runner to the connection class.

---

python/veles/async_client/conn.py
python/veles/async_client/proto.py
python/veles/async_conn/conn.py
python/veles/async_conn/plugin.py
python/veles/proto/messages.py
python/veles/server/conn.py
python/veles/server/proto.py

This just adds registration of trigger handlers - they're not called yet.

Triggers - plugin side.

---

python/list
python/listsub
python/make_blob
python/plugin
python/proxy
python/show
python/sub
python/test_dis
python/upload_elf

Fixes from altran's comments to https://github.com/codilime/veles/pull/167.

Nits from altran's comments

---

CMakeLists.txt
include/data/repack.h
include/parser/stream.h
python/veles/cpp/generate.py
python/veles/data/repack.py
python/veles/schema/model.py
test/data/repack.cc

This includes changes needed to create model that will have class
with additional custom code in C++ that inherits from generated code

Allow for transfer of Repacker class over network

---

include/util/settings/connection_client.h
src/util/settings/connection_client.cc

this PR contains only settings change, next one will include UI

added network profile support

---

include/visualization/panel.h
src/ui/hexeditwidget.cc
src/visualization/panel.cc

Filter out refresh for not visible visualizations

---

Jenkinsfile

To do it we use hubot-jenkins-notifier plugin for hubot - our RC bot

Add RC notifications instead of slack ones

---

python/delete
python/list
python/listsub
python/make_blob
python/plugin
python/proxy
python/show
python/srv.py
python/sub
python/upload_elf
python/veles/db/backend.py
python/veles/util/helpers.py
src/ui/connectionmanager.cc

Also allow to start server with in-memory database

Use argparse in Python server scripts

---

src/ui/hexedit.cc

fix for issue: https://github.com/codilime/veles/issues/235

move cursor when go to address

---

src/ui/searchdialog.cc

fix for https://github.com/codilime/veles/issues/236

search from cursor

---

src/ui/searchdialog.cc
src/ui/searchdialog.ui

Feature from issue: https://github.com/codilime/veles/issues/240

add possibility to find overlapping matches

---

README.rst

Add running instructions

---

include/ui/hexedit.h
include/ui/searchdialog.h
include/util/edit.h
src/ui/hexedit.cc
src/ui/searchdialog.cc
src/ui/searchdialog.ui
src/util/edit.cc
test/util/edit.cc

Modify EditEngine to use BinData

Enable support for replace in HexEdit

---

changelog.md
src/ui/connectionmanager.cc
src/util/version.cc

Fix startup issue after installing .deb package.
Initial patch submitted by: @p2004a

Add missing cert-dir argument when starting server

---

include/ui/fileblobmodel.h
include/ui/hexedit.h
include/ui/hexeditwidget.h
include/util/settings/shortcuts.h
src/ui/hexedit.cc
src/ui/hexeditwidget.cc
src/ui/nodewidget.cc
src/ui/optionsdialog.ui
src/util/settings/shortcuts.cc

https://github.com/codilime/veles/issues/260

Better columns number settings

---

include/ui/hexedit.h
include/util/settings/shortcuts.h
src/ui/hexedit.cc
src/util/settings/shortcuts.cc

Two options added:
- Select chunk
- Save chunk to file

Chunk utils

---

include/visualization/trigram.h
src/visualization/trigram.cc

trigram: Orthogonal projection.

---

include/ui/searchdialog.h
src/ui/searchdialog.cc
src/ui/searchdialog.ui

I added two buttons: "Find Previous" and "Replace Previous". (#262)
I'm not sure about add new function `replaceClick` actually I'm not sure about name of it. Can I add it?

Add buttons find/replace previous

---

include/visualization/panel.h
include/visualization/samplingmethoddialog.h
src/ui/connectionmanager.cc
src/ui/databaseinfo.cc
src/ui/dockwidget.cc
src/ui/fileblobitem.cc
src/ui/fileblobmodel.cc
src/ui/gotoaddressdialog.cc
src/ui/hexeditwidget.cc
src/ui/logwidget.cc
src/ui/nodewidget.cc
src/ui/rootfileblobitem.cc
src/ui/subchunkfileblobitem.cc
src/ui/veles_mainwindow.cc
src/visualization/minimap_panel.cc
src/visualization/panel.cc
src/visualization/samplingmethoddialog.cc
src/visualization/trigram.cc

Fixes #319.
Also added some refactoring to ensure that similar bug would not happen again.

Fix slot mismatch issue

---

CMakeLists.txt
resources/MacOSXBundleInfo.plist.in

Enable high-DPI support on macOS

---

include/util/edit.h
src/util/edit.cc

`remapOrigin` updates the address mapping after remapping request from server.

Add remapOrigin in EditEngine

---

include/client/networkclient.h
include/ui/connectiondialog.h
include/ui/connectionmanager.h
include/util/settings/connection_client.h
python/proxy
python/srv.py
python/veles/server/proto.py
python/veles/util/helpers.py
src/client/networkclient.cc
src/ui/connectiondialog.cc
src/ui/connectiondialog.ui
src/ui/connectionmanager.cc
src/util/settings/connection_client.cc

Fix networking part 2

---

src/ui/hexedit.cc

Fix garbage nibble when inserting a new byte

---

include/visualization/trigram.h
src/visualization/shaders/trigram/fshader.glsl
src/visualization/shaders/trigram/vshader.glsl
src/visualization/trigram.cc

Calculate nice gl_PointSize in trigram view.

---

src/visualization/manipulator.cc

Ensure manipulator quaternions are normalized.

---

src/util/settings/theme.cc

Dark theme as default

---

include/visualization/panel.h
include/visualization/trigram.h
src/visualization/panel.cc
src/visualization/trigram.cc

Add visual hint of current visualization modes and manipulators

---

src/ui/optionsdialog.ui

Fixed oversized options dialog

---

src/visualization/minimap.cc

Fix minimap crash on small files

---

src/ui/databaseinfo.cc

Fix highlighting item on hover in database tab.

---

include/ui/hexedit.h
src/ui/hexedit.cc

Remove empty space below data in hexedit. Change scrolling.

---

CMakeLists.txt
include/ui/dockwidget.h
include/ui/hexeditwidget.h
include/ui/optionsdialog.h
include/ui/velesapplication.h
include/visualization/trigram.h
src/ui/hexeditwidget.cc
src/ui/main.cc
src/ui/nodetreewidget.cc
src/ui/optionsdialog.cc
src/ui/optionsdialog.ui
src/ui/veles_mainwindow.cc
src/visualization/trigram.cc

I also refactored a bit the way we reload settings.

Add "Apply" button to the Options dialog

---

src/ui/dialogs/connectiondialog.cc

Fix cursor position in server url

---

include/ui/dialogs/optionsdialog.h
include/util/settings/hexedit.h
include/util/settings/theme.h
include/util/settings/visualization.h
src/ui/dialogs/optionsdialog.cc
src/ui/dialogs/optionsdialog.ui
src/util/settings/hexedit.cc
src/util/settings/theme.cc
src/util/settings/visualization.cc

Fixes #403
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/codilime/veles/406)

Add reset to defaults button to options

---

include/ui/disasm/disasm.h
include/ui/disasm/mocks.h
include/ui/disasm/row.h
src/ui/disasm/disasm.cc
src/ui/disasm/mocks.cc
src/ui/disasm/row.cc
src/ui/disasm/widget.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/codilime/veles/410)

Entry chunk collapsed.

---

include/ui/disasm/row.h
include/ui/disasm/widget.h
src/ui/disasm/mocks.cc
src/ui/disasm/row.cc
src/ui/disasm/widget.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/codilime/veles/411)

Collapse chunks on double clicks.

---

include/ui/disasm/row.h
include/ui/disasm/tab.h
include/ui/disasm/widget.h
src/ui/disasm/row.cc
src/ui/disasm/tab.cc
src/ui/disasm/widget.cc
src/ui/hexeditwidget.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/codilime/veles/409)

Disasm::toggleColumns

---

include/ui/disasm/arrows.h
include/ui/disasm/widget.h
src/ui/disasm/arrows.cc
src/ui/disasm/widget.cc

See doc on ArrowsWidget class
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/codilime/veles/413)

Rendering arrows widget

---

include/util/settings/theme.h
src/ui/main.cc
src/util/settings/shortcuts.cc
src/util/settings/theme.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/codilime/veles/412)

Fix 'pallete' typo

---

CMakeLists.txt

Fixes #333.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/codilime/veles/335)

Fix setting CMAKE_OSX_DEPLOYMENT_TARGET

---

CONTRIBUTING.md

Added info for potential developers
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/codilime/veles/399)

Add more info to Contributing.md

---

include/ui/hexedit.h
include/util/settings/hexedit.h
include/util/settings/theme.h
include/util/settings/visualization.h
src/ui/dialogs/optionsdialog.cc
src/ui/dialogs/optionsdialog.ui
src/ui/hexedit.cc
src/ui/main.cc
src/util/settings/hexedit.cc
src/util/settings/theme.cc
src/util/settings/visualization.cc

Finally I can use Comic Sans in Veles :)
Fixes #402.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/codilime/veles/423)

Selectable fonts

---

CMakeLists.txt
include/ui/disasm/arrows.h
include/ui/disasm/disasm.h
include/ui/disasm/row.h
resources/style.qss
resources/veles.qrc
src/ui/disasm/arrows.cc
src/ui/disasm/row.cc
src/ui/main.cc
src/ui/mainwindowwithdetachabledockwidgets.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/codilime/veles/419)

[Disasm] TextRepr interpretation

---

CMakeLists.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/codilime/veles/426)

Fix Clang compilation error on Linux
